### ISSUE TITLE
wget to github fail?

### ISSUE THREAD

**Issue by elafargue** [cityzendata/warp10-docker#2]
Somehow, on my system the Dockerfile wget command to Github always fails with a "connection reset by peer". Changing the command to curl works perfect, go figure... Just a heads up.

System: MacOS El Capitan 10.11.3 and docker 1.10.3

**Comment by hbs** [comment]
Thanks for the report, we might switch to curl altogether.

**Comment by LostInBrittany** [comment]
@elafargue can you verify that the version with `curl` works for you?
